### ISSUE TITLE
Virtualenv auto-activation broken

### ISSUE THREAD

**Issue by tavlima** [adlibre/python-bureaucrat#5]
Do I need to create and activate a virtualenv before running `bureaucrat init` or `bureaucrat` itself handles this?

**Comment by macropin** [comment]
`bureaucrat` should handle this when installed in a virtualenv. If it's not working for you then that would be a bug.

**Comment by macropin** [comment]
I've confirmed that the virtualenv is not being properly activated when bureaucrate is called directly

**Comment by macropin** [comment]
After further testing. I'm not able to reproduce. This shows the bureaucrat is working as expected when called without an active virtual environment:

```
# create working app dir / virtualenv
mkdir /tmp/test
cd /tmp/test/
curl --silent https://raw.githubusercontent.com/adlibre/python-bootstrap/master/bootstrap.sh | bash -s .venv bureaucrat
# configure minimal process and environment
echo 'test: bash test.sh $FOO' > Procfile
echo 'FOO=BAR' > .env
echo 'echo "Test results: $@"' > test.sh 
# run bureaucrat
.venv/bin/bureaucrat start test
```

Checking `test.log` shows it contains the expected output
